//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 10:54:13 AM CET 
//


package se.ib92.produceSoap.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.ib92.produceSoap.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.ib92.produceSoap.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllBuilds }
     * 
     */
    public GetAllBuilds createGetAllBuilds() {
        return new GetAllBuilds();
    }

    /**
     * Create an instance of {@link GetAllBuildsResponse }
     * 
     */
    public GetAllBuildsResponse createGetAllBuildsResponse() {
        return new GetAllBuildsResponse();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link GetBuilds }
     * 
     */
    public GetBuilds createGetBuilds() {
        return new GetBuilds();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link GetBuildsResponse }
     * 
     */
    public GetBuildsResponse createGetBuildsResponse() {
        return new GetBuildsResponse();
    }

    /**
     * Create an instance of {@link QueryBuilds }
     * 
     */
    public QueryBuilds createQueryBuilds() {
        return new QueryBuilds();
    }

    /**
     * Create an instance of {@link QueryBuildsResponse }
     * 
     */
    public QueryBuildsResponse createQueryBuildsResponse() {
        return new QueryBuildsResponse();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link ArrayOfSubterraURI }
     * 
     */
    public ArrayOfSubterraURI createArrayOfSubterraURI() {
        return new ArrayOfSubterraURI();
    }

    /**
     * Create an instance of {@link ArrayOfstring }
     * 
     */
    public ArrayOfstring createArrayOfstring() {
        return new ArrayOfstring();
    }

    /**
     * Create an instance of {@link Revision }
     * 
     */
    public Revision createRevision() {
        return new Revision();
    }

    /**
     * Create an instance of {@link ArrayOfRevision }
     * 
     */
    public ArrayOfRevision createArrayOfRevision() {
        return new ArrayOfRevision();
    }

    /**
     * Create an instance of {@link ArrayOfLocation }
     * 
     */
    public ArrayOfLocation createArrayOfLocation() {
        return new ArrayOfLocation();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ArrayOfUser }
     * 
     */
    public ArrayOfUser createArrayOfUser() {
        return new ArrayOfUser();
    }

    /**
     * Create an instance of {@link BuildTestResults }
     * 
     */
    public BuildTestResults createBuildTestResults() {
        return new BuildTestResults();
    }

    /**
     * Create an instance of {@link BuildLinkedWorkItem }
     * 
     */
    public BuildLinkedWorkItem createBuildLinkedWorkItem() {
        return new BuildLinkedWorkItem();
    }

    /**
     * Create an instance of {@link ArrayOfBuildLinkedWorkItem }
     * 
     */
    public ArrayOfBuildLinkedWorkItem createArrayOfBuildLinkedWorkItem() {
        return new ArrayOfBuildLinkedWorkItem();
    }

    /**
     * Create an instance of {@link EnumOptionId }
     * 
     */
    public EnumOptionId createEnumOptionId() {
        return new EnumOptionId();
    }

    /**
     * Create an instance of {@link Approval }
     * 
     */
    public Approval createApproval() {
        return new Approval();
    }

    /**
     * Create an instance of {@link ArrayOfApproval }
     * 
     */
    public ArrayOfApproval createArrayOfApproval() {
        return new ArrayOfApproval();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link ArrayOfAttachment }
     * 
     */
    public ArrayOfAttachment createArrayOfAttachment() {
        return new ArrayOfAttachment();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link ArrayOfCategory }
     * 
     */
    public ArrayOfCategory createArrayOfCategory() {
        return new ArrayOfCategory();
    }

    /**
     * Create an instance of {@link ArrayOfEnumOptionId }
     * 
     */
    public ArrayOfEnumOptionId createArrayOfEnumOptionId() {
        return new ArrayOfEnumOptionId();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link ArrayOfComment }
     * 
     */
    public ArrayOfComment createArrayOfComment() {
        return new ArrayOfComment();
    }

    /**
     * Create an instance of {@link ExternallyLinkedWorkItem }
     * 
     */
    public ExternallyLinkedWorkItem createExternallyLinkedWorkItem() {
        return new ExternallyLinkedWorkItem();
    }

    /**
     * Create an instance of {@link ArrayOfExternallyLinkedWorkItem }
     * 
     */
    public ArrayOfExternallyLinkedWorkItem createArrayOfExternallyLinkedWorkItem() {
        return new ArrayOfExternallyLinkedWorkItem();
    }

    /**
     * Create an instance of {@link Hyperlink }
     * 
     */
    public Hyperlink createHyperlink() {
        return new Hyperlink();
    }

    /**
     * Create an instance of {@link ArrayOfHyperlink }
     * 
     */
    public ArrayOfHyperlink createArrayOfHyperlink() {
        return new ArrayOfHyperlink();
    }

    /**
     * Create an instance of {@link LinkedOslcResource }
     * 
     */
    public LinkedOslcResource createLinkedOslcResource() {
        return new LinkedOslcResource();
    }

    /**
     * Create an instance of {@link ArrayOfLinkedOslcResource }
     * 
     */
    public ArrayOfLinkedOslcResource createArrayOfLinkedOslcResource() {
        return new ArrayOfLinkedOslcResource();
    }

    /**
     * Create an instance of {@link LinkedWorkItem }
     * 
     */
    public LinkedWorkItem createLinkedWorkItem() {
        return new LinkedWorkItem();
    }

    /**
     * Create an instance of {@link ArrayOfLinkedWorkItem }
     * 
     */
    public ArrayOfLinkedWorkItem createArrayOfLinkedWorkItem() {
        return new ArrayOfLinkedWorkItem();
    }

    /**
     * Create an instance of {@link Custom }
     * 
     */
    public Custom createCustom() {
        return new Custom();
    }

    /**
     * Create an instance of {@link ArrayOfCustom }
     * 
     */
    public ArrayOfCustom createArrayOfCustom() {
        return new ArrayOfCustom();
    }

    /**
     * Create an instance of {@link PlanningConstraint }
     * 
     */
    public PlanningConstraint createPlanningConstraint() {
        return new PlanningConstraint();
    }

    /**
     * Create an instance of {@link ArrayOfPlanningConstraint }
     * 
     */
    public ArrayOfPlanningConstraint createArrayOfPlanningConstraint() {
        return new ArrayOfPlanningConstraint();
    }

    /**
     * Create an instance of {@link PriorityOptionId }
     * 
     */
    public PriorityOptionId createPriorityOptionId() {
        return new PriorityOptionId();
    }

    /**
     * Create an instance of {@link TimePoint }
     * 
     */
    public TimePoint createTimePoint() {
        return new TimePoint();
    }

    /**
     * Create an instance of {@link WorkRecord }
     * 
     */
    public WorkRecord createWorkRecord() {
        return new WorkRecord();
    }

    /**
     * Create an instance of {@link ArrayOfWorkRecord }
     * 
     */
    public ArrayOfWorkRecord createArrayOfWorkRecord() {
        return new ArrayOfWorkRecord();
    }

    /**
     * Create an instance of {@link WorkItem }
     * 
     */
    public WorkItem createWorkItem() {
        return new WorkItem();
    }

    /**
     * Create an instance of {@link ArrayOfPriorityOptionId }
     * 
     */
    public ArrayOfPriorityOptionId createArrayOfPriorityOptionId() {
        return new ArrayOfPriorityOptionId();
    }

    /**
     * Create an instance of {@link EnumOption }
     * 
     */
    public EnumOption createEnumOption() {
        return new EnumOption();
    }

    /**
     * Create an instance of {@link PriorityOpt }
     * 
     */
    public PriorityOpt createPriorityOpt() {
        return new PriorityOpt();
    }

    /**
     * Create an instance of {@link CustomFieldType }
     * 
     */
    public CustomFieldType createCustomFieldType() {
        return new CustomFieldType();
    }

    /**
     * Create an instance of {@link EnumCustomFieldType }
     * 
     */
    public EnumCustomFieldType createEnumCustomFieldType() {
        return new EnumCustomFieldType();
    }

    /**
     * Create an instance of {@link PlanRecord }
     * 
     */
    public PlanRecord createPlanRecord() {
        return new PlanRecord();
    }

    /**
     * Create an instance of {@link ArrayOfPlanRecord }
     * 
     */
    public ArrayOfPlanRecord createArrayOfPlanRecord() {
        return new ArrayOfPlanRecord();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link ArrayOfPlan }
     * 
     */
    public ArrayOfPlan createArrayOfPlan() {
        return new ArrayOfPlan();
    }

}
