//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 10:54:13 AM CET 
//


package se.ib92.produceSoap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Plan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plan"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="allowedTypes" type="{http://ws.polarion.com/TrackerWebService-types}ArrayOfEnumOptionId" minOccurs="0"/&gt;
 *         &lt;element name="authorURI" type="{http://ws.polarion.com/types}SubterraURI" minOccurs="0"/&gt;
 *         &lt;element name="calculationType" type="{http://ws.polarion.com/TrackerWebService-types}EnumOptionId" minOccurs="0"/&gt;
 *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="defaultEstimate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://ws.polarion.com/types}Text" minOccurs="0"/&gt;
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="estimationField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="finishedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="homePageContent" type="{http://ws.polarion.com/types}Text" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="location" type="{http://ws.polarion.com/types}Location" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parent" type="{http://ws.polarion.com/PlanningWebService-types}Plan" minOccurs="0"/&gt;
 *         &lt;element name="previousTimeSpent" type="{http://ws.polarion.com/types}duration" minOccurs="0"/&gt;
 *         &lt;element name="prioritizationField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="projectURI" type="{http://ws.polarion.com/types}SubterraURI" minOccurs="0"/&gt;
 *         &lt;element name="projectSpanURIs" type="{http://ws.polarion.com/types}ArrayOfSubterraURI" minOccurs="0"/&gt;
 *         &lt;element name="records" type="{http://ws.polarion.com/PlanningWebService-types}ArrayOfPlanRecord" minOccurs="0"/&gt;
 *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="startedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://ws.polarion.com/TrackerWebService-types}EnumOptionId" minOccurs="0"/&gt;
 *         &lt;element name="templateURI" type="{http://ws.polarion.com/types}SubterraURI" minOccurs="0"/&gt;
 *         &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="useReportFromTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="customFields" type="{http://ws.polarion.com/TrackerWebService-types}ArrayOfCustom" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="uri" type="{http://ws.polarion.com/types}SubterraURI" /&gt;
 *       &lt;attribute name="unresolvable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plan", namespace = "http://ws.polarion.com/PlanningWebService-types", propOrder = {
    "allowedTypes",
    "authorURI",
    "calculationType",
    "capacity",
    "color",
    "created",
    "defaultEstimate",
    "description",
    "dueDate",
    "estimationField",
    "finishedOn",
    "homePageContent",
    "id",
    "isTemplate",
    "location",
    "name",
    "parent",
    "previousTimeSpent",
    "prioritizationField",
    "projectURI",
    "projectSpanURIs",
    "records",
    "sortOrder",
    "startDate",
    "startedOn",
    "status",
    "templateURI",
    "updated",
    "useReportFromTemplate",
    "customFields"
})
public class Plan {

    protected ArrayOfEnumOptionId allowedTypes;
    protected String authorURI;
    protected EnumOptionId calculationType;
    protected Float capacity;
    protected String color;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar created;
    protected Float defaultEstimate;
    protected Text description;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    protected String estimationField;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar finishedOn;
    protected Text homePageContent;
    protected String id;
    protected Boolean isTemplate;
    protected String location;
    protected String name;
    protected Plan parent;
    protected String previousTimeSpent;
    protected String prioritizationField;
    protected String projectURI;
    protected ArrayOfSubterraURI projectSpanURIs;
    protected ArrayOfPlanRecord records;
    protected Integer sortOrder;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startedOn;
    protected EnumOptionId status;
    protected String templateURI;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    protected Boolean useReportFromTemplate;
    protected ArrayOfCustom customFields;
    @XmlAttribute(name = "uri")
    protected String uri;
    @XmlAttribute(name = "unresolvable")
    protected Boolean unresolvable;

    /**
     * Gets the value of the allowedTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfEnumOptionId }
     *     
     */
    public ArrayOfEnumOptionId getAllowedTypes() {
        return allowedTypes;
    }

    /**
     * Sets the value of the allowedTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfEnumOptionId }
     *     
     */
    public void setAllowedTypes(ArrayOfEnumOptionId value) {
        this.allowedTypes = value;
    }

    /**
     * Gets the value of the authorURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorURI() {
        return authorURI;
    }

    /**
     * Sets the value of the authorURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorURI(String value) {
        this.authorURI = value;
    }

    /**
     * Gets the value of the calculationType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumOptionId }
     *     
     */
    public EnumOptionId getCalculationType() {
        return calculationType;
    }

    /**
     * Sets the value of the calculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumOptionId }
     *     
     */
    public void setCalculationType(EnumOptionId value) {
        this.calculationType = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCapacity(Float value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreated(XMLGregorianCalendar value) {
        this.created = value;
    }

    /**
     * Gets the value of the defaultEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDefaultEstimate() {
        return defaultEstimate;
    }

    /**
     * Sets the value of the defaultEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDefaultEstimate(Float value) {
        this.defaultEstimate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setDescription(Text value) {
        this.description = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the estimationField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimationField() {
        return estimationField;
    }

    /**
     * Sets the value of the estimationField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimationField(String value) {
        this.estimationField = value;
    }

    /**
     * Gets the value of the finishedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinishedOn() {
        return finishedOn;
    }

    /**
     * Sets the value of the finishedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinishedOn(XMLGregorianCalendar value) {
        this.finishedOn = value;
    }

    /**
     * Gets the value of the homePageContent property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getHomePageContent() {
        return homePageContent;
    }

    /**
     * Sets the value of the homePageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setHomePageContent(Text value) {
        this.homePageContent = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTemplate(Boolean value) {
        this.isTemplate = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link Plan }
     *     
     */
    public Plan getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan }
     *     
     */
    public void setParent(Plan value) {
        this.parent = value;
    }

    /**
     * Gets the value of the previousTimeSpent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousTimeSpent() {
        return previousTimeSpent;
    }

    /**
     * Sets the value of the previousTimeSpent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousTimeSpent(String value) {
        this.previousTimeSpent = value;
    }

    /**
     * Gets the value of the prioritizationField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrioritizationField() {
        return prioritizationField;
    }

    /**
     * Sets the value of the prioritizationField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrioritizationField(String value) {
        this.prioritizationField = value;
    }

    /**
     * Gets the value of the projectURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectURI() {
        return projectURI;
    }

    /**
     * Sets the value of the projectURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectURI(String value) {
        this.projectURI = value;
    }

    /**
     * Gets the value of the projectSpanURIs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public ArrayOfSubterraURI getProjectSpanURIs() {
        return projectSpanURIs;
    }

    /**
     * Sets the value of the projectSpanURIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public void setProjectSpanURIs(ArrayOfSubterraURI value) {
        this.projectSpanURIs = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPlanRecord }
     *     
     */
    public ArrayOfPlanRecord getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPlanRecord }
     *     
     */
    public void setRecords(ArrayOfPlanRecord value) {
        this.records = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSortOrder(Integer value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the startedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartedOn() {
        return startedOn;
    }

    /**
     * Sets the value of the startedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartedOn(XMLGregorianCalendar value) {
        this.startedOn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EnumOptionId }
     *     
     */
    public EnumOptionId getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumOptionId }
     *     
     */
    public void setStatus(EnumOptionId value) {
        this.status = value;
    }

    /**
     * Gets the value of the templateURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateURI() {
        return templateURI;
    }

    /**
     * Sets the value of the templateURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateURI(String value) {
        this.templateURI = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * Gets the value of the useReportFromTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseReportFromTemplate() {
        return useReportFromTemplate;
    }

    /**
     * Sets the value of the useReportFromTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseReportFromTemplate(Boolean value) {
        this.useReportFromTemplate = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCustom }
     *     
     */
    public ArrayOfCustom getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCustom }
     *     
     */
    public void setCustomFields(ArrayOfCustom value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the unresolvable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnresolvable() {
        return unresolvable;
    }

    /**
     * Sets the value of the unresolvable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnresolvable(Boolean value) {
        this.unresolvable = value;
    }

}
