//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 10:54:13 AM CET 
//


package se.ib92.produceSoap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriorityOpt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriorityOpt"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.polarion.com/TrackerWebService-types}EnumOption"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="float" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriorityOpt", propOrder = {
    "_float"
})
public class PriorityOpt
    extends EnumOption
{

    @XmlElement(name = "float")
    protected float _float;

    /**
     * Gets the value of the float property.
     * 
     */
    public float getFloat() {
        return _float;
    }

    /**
     * Sets the value of the float property.
     * 
     */
    public void setFloat(float value) {
        this._float = value;
    }

}
