//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 10:54:13 AM CET 
//


package se.ib92.produceSoap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for User complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="User"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://ws.polarion.com/types}Text" minOccurs="0"/&gt;
 *         &lt;element name="disabledNotifications" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="homePageContent" type="{http://ws.polarion.com/types}Text" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="voteURIs" type="{http://ws.polarion.com/types}ArrayOfSubterraURI" minOccurs="0"/&gt;
 *         &lt;element name="watcheURIs" type="{http://ws.polarion.com/types}ArrayOfSubterraURI" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="uri" type="{http://ws.polarion.com/types}SubterraURI" /&gt;
 *       &lt;attribute name="unresolvable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", namespace = "http://ws.polarion.com/ProjectWebService-types", propOrder = {
    "description",
    "disabledNotifications",
    "email",
    "homePageContent",
    "id",
    "name",
    "voteURIs",
    "watcheURIs"
})
public class User {

    protected Text description;
    protected Boolean disabledNotifications;
    protected String email;
    protected Text homePageContent;
    protected String id;
    protected String name;
    protected ArrayOfSubterraURI voteURIs;
    protected ArrayOfSubterraURI watcheURIs;
    @XmlAttribute(name = "uri")
    protected String uri;
    @XmlAttribute(name = "unresolvable")
    protected Boolean unresolvable;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setDescription(Text value) {
        this.description = value;
    }

    /**
     * Gets the value of the disabledNotifications property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabledNotifications() {
        return disabledNotifications;
    }

    /**
     * Sets the value of the disabledNotifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabledNotifications(Boolean value) {
        this.disabledNotifications = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the homePageContent property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getHomePageContent() {
        return homePageContent;
    }

    /**
     * Sets the value of the homePageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setHomePageContent(Text value) {
        this.homePageContent = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the voteURIs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public ArrayOfSubterraURI getVoteURIs() {
        return voteURIs;
    }

    /**
     * Sets the value of the voteURIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public void setVoteURIs(ArrayOfSubterraURI value) {
        this.voteURIs = value;
    }

    /**
     * Gets the value of the watcheURIs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public ArrayOfSubterraURI getWatcheURIs() {
        return watcheURIs;
    }

    /**
     * Sets the value of the watcheURIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSubterraURI }
     *     
     */
    public void setWatcheURIs(ArrayOfSubterraURI value) {
        this.watcheURIs = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the unresolvable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnresolvable() {
        return unresolvable;
    }

    /**
     * Sets the value of the unresolvable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnresolvable(Boolean value) {
        this.unresolvable = value;
    }

}
